### ISSUE TITLE
Default OS repositories layout messed up by yum module

### ISSUE THREAD

**Issue by cpeetersburg** [voxpupuli/puppet-yum#132]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.10
- Ruby: 2.4.5p33
- Distribution: Centos 7.6.1810
- Module version: 3.1.1

## How to reproduce (e.g Puppet code you use)

I'm using roles and profiles so this is in my `site/profile/manifests/base.pp`
```
class { 'yum':
  manage_os_default_repos => true,
}
```
This is in my `data/common.yaml`
```
yum::managed_repos:
  - 'base'
  - 'updates'
  - 'extras'
  - 'centosplus'
  - 'example'
yum::repos:
  base:
    enabled: true
    baseurl: 'http://repo.example.org/CentOS/$releasever/os/$basearch/'
    mirrorlist: 'absent'
  updates:
    enabled: true
    baseurl: 'http://repo.example.org/CentOS/$releasever/updates/$basearch/'
    mirrorlist: 'absent'
  extras:
    enabled: true
    baseurl: 'http://repo.example.org/CentOS/$releasever/extras/$basearch/'
    mirrorlist: 'absent'
  centosplus:
    enabled: true
    baseurl: 'http://repo.example.org/CentOS/$releasever/centosplus/$basearch/'
    mirrorlist: 'absent'
  example:
    ensure: 'present'
    enabled: true
    descr: 'Example Repository'
    baseurl: 'http://repo.example.org/example/'
    gpgcheck: false
    target: '/etc/yum.repos.d/example.repo'
```

## What are you seeing

When using the yum module to manage the default repositories, I get a messed up repofile. It still works, but it looks very chaotic because the whitespaces aren't correct. See the example below.

/etc/yum/repos.d/CentOS-Base.repo
```
[base]
name=CentOS-$releasever - Base
#baseurl=http://mirror.centos.org/centos/$releasever/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
 
#released updates
baseurl=http://repo.example.org/CentOS/$releasever/os/$basearch/
enabled=1
[updates]
name=CentOS-$releasever - Updates
#baseurl=http://mirror.centos.org/centos/$releasever/updates/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
```
## What behaviour did you expect instead
/etc/yum/repos.d/CentOS-Base.repo
```
[base]
name=CentOS-$releasever - Base
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
baseurl=http://repo.example.org/CentOS/$releasever/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

#released updates
[updates]
name=CentOS-$releasever - Updates
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updatesinfra=$infra
baseurl=http://repo.example.org/CentOS/$releasever/updates/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
```

## Any additional information you'd like to impart
The example repository is looking fine. There's a separate example.repo file which has the following contents:
```
[example]
name=Example Repository
baseurl=http://repo.example.org/example/
enabled=1
gpgcheck=0
```

In attachment also the CentOS-Base.repo file in 3 different versions (added .txt for Github support):
- [CentOS-Base.repo.txt](https://github.com/voxpupuli/puppet-yum/files/2876228/CentOS-Base.repo.txt): the file as found on a freshly installed CentOS 7
- [CentOS-Base-expected.repo.txt](https://github.com/voxpupuli/puppet-yum/files/2876229/CentOS-Base-expected.repo.txt): the file as I would expect it after the puppet run has completed
- [CentOS-Base-reality.repo.txt](https://github.com/voxpupuli/puppet-yum/files/2876230/CentOS-Base-reality.repo.txt): the file as it really is after the puppet run has completed
