### ISSUE TITLE
Module expects http://, https:// or file:// as baseurl without checking other yum plugins that do so

### ISSUE THREAD

**Issue by Voovode** [voxpupuli/puppet-yum#151]
## Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Ruby: 2.4.9p362
- Distribution: CentOS 7
- Module version: 4.0.0

## How to reproduce (e.g Puppet code you use)
Hiera values below:

```
yum::managed_repos:
    - 'my-project'
yum::repos:
    my-project:
        ensure: 'present'
        enabled: true
        descr: 'My Project Repo'
        baseurl: "gs://my-project-%{::envname}-repo/myproject"
        gpgcheck: false
        gpgkey: '--'
        target: '/etc/yum.repos.d/my-project.repo'
```

eg. try to use a different baseurl, other than **http/https/file**, like me above.

## What are you seeing
I'm using the [yum-gs-iam plugin](https://github.com/Voovode/yum-gs-iam) for yum, which allows yum to be able to fetch packages from GCS.

puppet-yum plugin will try to validate baseurl without letting yum do so.

## What behaviour did you expect instead
Since I've got a yum plugin installed to handle the **gs://** baseurl, module should not check it?

## Output log

> Dec 02 12:14:33 test-server puppet[1848]: Error: Parameter baseurl failed on Yumrepo[spareroom-secure]: Validate method failed for class baseurl: Must be a valid URL at /etc/puppetlabs/code/modules/yum/manifests/init.pp:136
