### ISSUE TITLE
No Repos getting added

### ISSUE THREAD

**Issue by sam-cogan** [voxpupuli/puppet-yum#168]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 2018.1.3
- Ruby:
- Distribution: centos
- Module version:4.1.1

## How to reproduce (e.g Puppet code you use)
```
yum::managed_repos:
    - 'azure_cli'
    - 'kubernetes'
yum::repos:
  azure_cli:
    ensure: 'present'
    enabled: true
    descr: 'Repo for Azure CLI'
    baseurl: 'https://packages.microsoft.com/yumrepos/azure-cli/'
    gpgcheck: true
    gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
    target: '/etc/yum.repos.d/azure_cli.repo'
  kubernetes:
    ensure: 'present'
    enabled: true
    descr: 'Repo for Kubernetes'
    baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/'
    gpgcheck: false
    gpgkey: 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'
    target: '/etc/yum.repos.d/kubernetes.repo'
```
## What are you seeing
I am trying to setup two additional yum repos. I have followed the docs and setup the hieradata as above, however this does not appear to work. No errors occur during Puppet apply, however the repos are not added and I cannot install any packages from those repos. Am I doing anything obviously wrong?
## What behaviour did you expect instead
Repos to be added
