### ISSUE TITLE
Add CentOS 8 repositories

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-yum#176]
Currently, module doesn't define/manage CentOS8 repositories.

I locally added the following configuration in CentOS-8.yaml
```
lookup_options:
  yum::os_default_repos:
    merge: first

yum::os_default_repos:
  - AppStream
  - BaseOS
  - cr
  - extras
  - PowerTools

yum::repos:
  AppStream:
    enabled: true
    descr: 'CentOS-$releasever - AppStream'
    mirrorlist: 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=AppStream&infra=$infra'
    gpgcheck: true
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
    target: '/etc/yum.repos.d/CentOS-AppStream.repo'
  BaseOS:
    enabled: true
    descr: 'CentOS-$releasever - Base'
    mirrorlist: 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=BaseOS&infra=$infra'
    gpgcheck: true
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
    target: '/etc/yum.repos.d/CentOS-Base.repo'
  cr:
    enabled: false
    descr: 'CentOS-$releasever - cr'
    baseurl: 'http://mirror.centos.org/$contentdir/$releasever/cr/$basearch/os/'
    gpgcheck: true
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
    target: '/etc/yum.repos.d/CentOS-CR.repo'
  extras:
    enabled: true
    descr: 'CentOS-$releasever - Extras'
    mirrorlist: 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra'
    gpgcheck: true
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
    target: '/etc/yum.repos.d/CentOS-Extras.repo'
  PowerTools:
    enabled: false
    descr: 'CentOS-$releasever - PowerTools'
    mirrorlist: 'http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=PowerTools&infra=$infra'
    gpgcheck: true
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
    target: '/etc/yum.repos.d/CentOS-PowerTools.repo'
```
