### ISSUE TITLE
Feature Request: Allow to specify multiple gpgkeys in yum::repos

### ISSUE THREAD

**Issue by fetzerms** [voxpupuli/puppet-yum#199]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.19.1
- Ruby:  Bundles with puppet agent: 2.5.8p224
- Distribution: RHEL7
- Module version: 4.1.0

## How to reproduce (e.g Puppet code you use)
It is possible to specify multiple GPG keys for a single repo, so packages can be signed with either key.
For example, this happens for the recent official puppetlabs repositories. So two gpg keys need to be 
added to the repo configuration in /etc/yum/repos.d/

What we have now:
```
yum::repos:
  puppet6:
    ensure: 'present'
    enabled: true
    descr: 'Puppet 6 Repository el 7 - $basearch'
    baseurl: 'ourrepohosthere/rpm/puppet6/el/7/$basearch'
    gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-puppet6-release'
    gpgcheck: false
```

## What are you seeing

I see, that I can only specify a single key for gpgkey.

## What behaviour did you expect instead

What we need:
```
yum::repos:
  puppet6:
    ensure: 'present'
    enabled: true
    descr: 'Puppet 6 Repository el 7 - $basearch'
    baseurl: 'ourrepohosthere/rpm/puppet6/el/7/$basearch'
    gpgkey: 
      - 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-puppet6-release'
      - 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-2025-04-06-puppet-release'
    gpgcheck: false
```
## Output log
n/a
