### ISSUE TITLE
removal of mirrorlist is set by 'absent' not by using a knockout.

### ISSUE THREAD

**Issue by shawn-sterling** [voxpupuli/puppet-yum#63]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-agent-1.9.3-1.el6.x86_64
- Ruby: Puppet-Agent packages 2.1.0
- Distribution: Centos 6
- Module version:  2.0.1-rc0

## How to reproduce (e.g Puppet code you use)
Pass hiera data using a knockout for mirrorlist

```
yum::managed_repos:
  - 'base'

yum::manage_os_default_repos: false

yum::repos:
  base:
    enabled: true
    descr: 'CentOS-$releasever - Base'
    baseurl: 'https://my.artifactory.server/yum-centos/$releasever/os/$basearch/'
    mirrorlist: '--'
    gpgcheck: true
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-%{facts.os.release.major}"
    target: '/etc/yum.repos.d/CentOS-Base.repo'
```
## What are you seeing

```
Error: Parameter mirrorlist failed on Yumrepo[base]: Validate method failed for class mirrorlist: Must be a valid URL at /etc/puppetlabs/code/environments/production/modules/yum/manifests/init.pp:130
```

## What behaviour did you expect instead

The yumrepo resource is expecting 'absent' for mirrorlist not undef. 

## Any additional information you'd like to impart

Works fine if I set the mirrorlist to 'absent' , think this just needs an update to the documentation, or maybe you want to tackle this another way?

Have a good day.

-Shawn
