### ISSUE TITLE
Feature Request: purge

### ISSUE THREAD

**Issue by TJM** [voxpupuli/puppet-yum#94]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-agent-5.3.5-1.el7.x86_64
- Ruby: ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
- Distribution: CentOS
- Module version: 2.2.1

## How to reproduce (e.g Puppet code you use)

```
include ::yum
```

## What are you seeing
New repos are added, but old ones are not removed

## What behaviour did you expect instead
I expect the old ones to be removed.

## Any additional information you'd like to impart

I think we should add a parameter:
```
  Boolean $purge = true,
```

... and add the following puppet code:

```
resources { 'yumrepo':
  purge => $purge,
}
```

**Comment by dhoppe** [comment]
I need more information about your workflow and how you added / removed the repositories. If you want to remove some of the repositories you could use something like this:
```
[vagrant@centos-7 yum]$ cat data/common.yaml
---
yum::managed_repos:
  - 'base'
  - 'updates'
  - 'extras'
  - 'centosplus'
yum::repos:
  base:
    ensure: 'absent'
  updates:
    ensure: 'absent'
  extras:
    ensure: 'absent'
  centosplus:
    ensure: 'absent'
```

```
[vagrant@centos-7 yum]$ sudo /opt/puppetlabs/bin/puppet apply --modulepath=/home/vagrant/projects/modules -e 'include yum'
Notice: Compiled catalog for centos-7.vagrant.dev in environment production in 0.23 seconds
Notice: /Stage[main]/Yum/Yumrepo[base]/ensure: removed
Notice: /Stage[main]/Yum/Yumrepo[updates]/ensure: removed
Notice: /Stage[main]/Yum/Yumrepo[extras]/ensure: removed
Notice: /Stage[main]/Yum/Yumrepo[centosplus]/ensure: removed
Notice: Applied catalog in 0.15 seconds
```
